/*
 * Description: This file represents the Employee Task View Model class
 * Author: Mtsharif 
 * Date: 18/4/2018
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using WorkflowManagementSystem.Models;

namespace WorkflowManagementSystem.ViewModels
{
    /// <summary>
    /// This view model is created based on the EmployeeTask domain model to be used in the EmployeeTask controller.
    /// </summary>
    public class EmployeeTaskViewModel
    {
        public EmployeeTaskViewModel()
        {
            TaskAssignments = new List<TaskAssignment>();
        }

        [Key]
        public int EmployeeTaskId { get; set; }

        [Required]
        [Display(Name = "Task Name")]
        public string Name { get; set; }

        [Display(Name = "Description")]
        [DisplayFormat(NullDisplayText = "Description Not Available")]
        [DataType(DataType.MultilineText)]
        public string Description { get; set; }

        [Display(Name = "Deadline")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true, NullDisplayText = "Deadline Not Available")]
        public DateTime Deadline { get; set; }

        [Display(Name = "Status")]
        public TaskStatus Status { get; set; }

        [Display(Name = "Priority")]
        public TaskPriority Priority { get; set; }

        // Task for which event project
        public int EventProjectId { get; set; }

        [Display(Name = "Event Project")]
        public string EventProject { get; set; }

        // Task generated by whom
        public int ClientServiceEmployeeId { get; set; }

        [Display(Name = "Created By")]
        public string Employee { get; set; }

        public List<TaskAssignment> TaskAssignments { get; set; }
    }
}